spring:
  application:
    name: resource
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999
  data:
    mongodb:
      database: test
      username: user
      password: password
      host: localhost
      port: 27017
      authentication-database: admin
server:
  port: 9010