spring:
  application:
    name: authorization
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: user
    password: password
  sql:
    init:
      mode: always
server:
  port: 9999